test5

diff --git a/.github/workflows/daily-sync.yaml b/.github/workflows/daily-sync.yaml
--- a/.github/workflows/daily-sync.yaml
+++ b/.github/workflows/daily-sync.yaml
@@ -41,6 +41,13 @@ jobs:
         run: |
           cd cmd
           go build -o ../certsuite-overview
+      
+      - name: Verify certsuite-overview exists
+        run: |
+          if [ ! -f ./certsuite-overview ]; then
+            echo "certsuite-overview binary is missing!"
+            exit 1
+          fi
 
       - name: Create Prometheus config file
         run: |
@@ -72,6 +79,18 @@ jobs:
           ./certsuite-overview > logs.txt 2>&1 &
           sleep 5
           cat logs.txt
+
+      - name: Check if certsuite-overview is running
+        run: |
+          if ! pgrep -f "certsuite-overview"; then
+            echo "certsuite-overview is NOT running!"
+            exit 1
+          else
+            echo "certsuite-overview is running."
+          fi
+
+      - name: Check if port 7000 is in use
+        run: netstat -tlnp || ss -tlnp
 
       - name: Wait for certsuite-overview to start listening
         run: |
